### ISSUE TITLE
curses.h file missing

### ISSUE THREAD

**Issue by oscarmageddon** [aguegu/greenrain#1]
when i run make command, i got error "#include <curses.h>" : no such file or directory

**Comment by oscarmageddon** [comment]
> when i run make command, i got error "#include <curses.h>" : no such file or directory

oh my bad sorry, i've installed libncurses5-dev and libncursesw5-dev and its works!!

**Comment by oscarmageddon** [comment]
i've installed libncurses5-dev and libncursesw5-dev and its works!!

**Comment by aguegu** [comment]
Great. You figured it out. Enjoy the code and feel free to show your outcome. :)

**Comment by oscarmageddon** [comment]
when i run make command, the aplication was compiled like an "application/x-sharedlib" and i can't run it anyways.

**Comment by aguegu** [comment]
It only runs in terminals.

**Comment by oscarmageddon** [comment]
i tried witth sh a bash commands but i can't

**Comment by aguegu** [comment]
What is the 'ls -l' output after make ?

**Comment by oscarmageddon** [comment]
-rwxrwxr-x 1 oscar oscar 212K mar 26 13:33 greenrain

**Comment by aguegu** [comment]
Just try "./greenrain"

**Comment by oscarmageddon** [comment]
u.u

**Comment by aguegu** [comment]
Anything?

**Comment by oscarmageddon** [comment]
it works, thnak you... O.o, that was the only cmmd that i didn't try

**Comment by aguegu** [comment]
Enjoy this 8 years old code. :)

**Comment by oscarmageddon** [comment]
nice, but Neo still doesn't appear
